# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd05a389c82088c2524b91fb015c0a4364aa976c45a263e00380760f7933e8ba7a1827c804e28760b1c8f4c0df48d98448236be8467073f929de222d6b9e024

test:
  secret_key_base: 5d0adfe7cc2c2a94b52663d9cffbac37943c02685400f0d4ac27e44ab7a7d7cf3314da7ac4d4b56d3b1f0902ff9b2060e5c0a238f95b8ad2e5b787fa79102c20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
